# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hlwN-KOVfLAP3iaY2Cy5k4DnRA0_P3U3
"""

import math
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.svm import LinearSVC
from sklearn.linear_model import Lasso
from sklearn.linear_model import LogisticRegression


def my_map(X_raw):
    # Transform X_raw into d using element-wise computation
    d = np.flip(2 * X_raw - 1, axis=1)
    X = np.cumprod(d, axis=1)
    mask = np.triu(np.ones((32, 32), dtype=bool), k=1)
    pairs = X[:, :, np.newaxis] * X[:, np.newaxis, :]
    pairs_masked = pairs[:, mask]
    X_new = np.concatenate([X, pairs_masked], axis=1)

    return X_new

def my_fit(X_raw, y):
    X = my_map(X_raw) 
    classifier = LogisticRegression(C=100,random_state=0)
    classifier.fit(X, y)
    w = classifier.coef_[0]  
    b = classifier.intercept_[0]  
    return w,b